package vn.onepay.cdr.filter.model;

// Generated May 8, 2014 3:26:47 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * SmsCdrFilter generated by hbm2java
 */
@SuppressWarnings("serial")
public class SmsCdrFilter implements java.io.Serializable, Cloneable {

	private Integer id;
	private String transactionRef;
	private String msisdn;
	private String merchant;
	private String serviceNumber;
	private String commandCode;
	private String contentService;
	private String chargingService;
	private String paymentProvider;
	private String telco;
	private BigDecimal amount;
	private Date chargingTime;
	private Date createdTime;
	private Date updatedTime;
	private int totalSMS;
	private int totalMSISDN;

	
	public SmsCdrFilter clone() {
		try {
			return (SmsCdrFilter) super.clone();
		} catch (CloneNotSupportedException e) {
            // This should never happen
            throw new InternalError(e.toString());
        }
	}
	
	public SmsCdrFilter() {
	}

	public SmsCdrFilter(String transactionRef, String msisdn, String merchant, String serviceNumber, String commandCode,
			String contentService, String chargingService,
			String paymentProvider, String telco, BigDecimal amount,
			Date chargingTime, Date createdTime, Date updatedTime) {
		this.transactionRef = transactionRef;
		this.msisdn = msisdn;
		this.merchant = merchant;
		this.serviceNumber = serviceNumber;
		this.commandCode = commandCode;
		this.contentService = contentService;
		this.chargingService = chargingService;
		this.paymentProvider = paymentProvider;
		this.telco = telco;
		this.amount = amount;
		this.chargingTime = chargingTime;
		this.createdTime = createdTime;
		this.updatedTime = updatedTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getTransactionRef() {
		return this.transactionRef;
	}

	public void setTransactionRef(String transactionRef) {
		this.transactionRef = transactionRef;
	}

	public String getMsisdn() {
		return msisdn;
	}
	
	public void setMsisdn(String msisdn) {
		this.msisdn = msisdn;
	}
	
	public String getMerchant() {
		return this.merchant;
	}

	public void setMerchant(String merchant) {
		this.merchant = merchant;
	}

	public String getServiceNumber() {
		return serviceNumber;
	}
	
	public void setServiceNumber(String serviceNumber) {
		this.serviceNumber = serviceNumber;
	}
	
	public String getCommandCode() {
		return commandCode;
	}
	
	public void setCommandCode(String commandCode) {
		this.commandCode = commandCode;
	}
	
	public String getContentService() {
		return this.contentService;
	}

	public void setContentService(String contentService) {
		this.contentService = contentService;
	}

	public String getChargingService() {
		return this.chargingService;
	}

	public void setChargingService(String chargingService) {
		this.chargingService = chargingService;
	}

	public String getPaymentProvider() {
		return this.paymentProvider;
	}

	public void setPaymentProvider(String paymentProvider) {
		this.paymentProvider = paymentProvider;
	}

	public String getTelco() {
		return this.telco;
	}

	public void setTelco(String telco) {
		this.telco = telco;
	}

	public BigDecimal getAmount() {
		return this.amount;
	}

	public void setAmount(BigDecimal amount) {
		this.amount = amount;
	}

	public Date getChargingTime() {
		return this.chargingTime;
	}

	public void setChargingTime(Date chargingTime) {
		this.chargingTime = chargingTime;
	}

	public Date getCreatedTime() {
		return this.createdTime;
	}

	public void setCreatedTime(Date createdTime) {
		this.createdTime = createdTime;
	}

	public Date getUpdatedTime() {
		return this.updatedTime;
	}

	public void setUpdatedTime(Date updatedTime) {
		this.updatedTime = updatedTime;
	}

	public int getTotalSMS() {
		return totalSMS;
	}
	
	public void setTotalSMS(int totalSMS) {
		this.totalSMS = totalSMS;
	}
	
	public int getTotalMSISDN() {
		return totalMSISDN;
	}
	
	public void setTotalMSISDN(int totalMSISDN) {
		this.totalMSISDN = totalMSISDN;
	}
}
