/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-11-04 09:04:58 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layouts.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class merchant_002drefund_css_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("\t.a_tag a{\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #2c8f39;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 5px 0px 5px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".a_tag a:HOVER {\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tcolor: #2c8f39;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 5px 0px 5px 0px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input_txt{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".input_number{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".select_style{\r\n");
      out.write("\twidth: 40%;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".textarea_style{\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\t/* margin-left: 5%; */\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_al_right{\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".text_al_left{\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".select_full_style{\r\n");
      out.write("\twidth: 90%;\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content_left{\r\n");
      out.write("\tmin-height: 30px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("\t\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\tcolor: #2C8F39;\r\n");
      out.write("\tline-height: 30px;\r\n");
      out.write("\t\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".content{\r\n");
      out.write("\theight: 30px;\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("\t\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("\t/* color: #2C8F39; */\r\n");
      out.write("\t/* line-height: 30px; */\r\n");
      out.write("\t\r\n");
      out.write("\twidth : 80%; height: auto; \r\n");
      out.write("\tfloat : left; margin-bottom: 10px; background: #F9F9F9; \r\n");
      out.write("\tpadding: 10px; border-radius: 5px 5px 5px 5px; \r\n");
      out.write("\tfont-weight: normal;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".bottom_border_span{\r\n");
      out.write("\twidth: 100%; display: block; border-bottom: 1px solid #CCCCCC;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#form_info table{\r\n");
      out.write("\t\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("#form_info table tr{\r\n");
      out.write("\tpadding: 5px;\r\n");
      out.write("}\r\n");
      out.write("#form_info table tr td:FIRST-CHILD{\r\n");
      out.write("\twidth: 30%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".width50{\r\n");
      out.write("\twidth: 50px;\r\n");
      out.write("}\r\n");
      out.write(".width60{\r\n");
      out.write("\twidth: 60px;\r\n");
      out.write("}\r\n");
      out.write(".width10{\r\n");
      out.write("\twidth: 10px;\r\n");
      out.write("}\r\n");
      out.write(".width15{\r\n");
      out.write("\twidth: 15px;\r\n");
      out.write("}\r\n");
      out.write(".width20{\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("}\r\n");
      out.write(".width80{\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".width90{\r\n");
      out.write("\twidth: 80px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".width100{\r\n");
      out.write("\twidth: 100px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".width120{\r\n");
      out.write("\twidth: 120px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".width200{\r\n");
      out.write("\twidth: 200px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".add_record , .add_record:HOVER{\r\n");
      out.write("\tbackground: url(\"");
      out.print(request.getContextPath());
      out.write("/images/add.png\") no-repeat scroll left center, url(\"");
      out.print(request.getContextPath());
      out.write("/images/btngreen_bg.png\") repeat-x scroll center top;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("\tpadding-left: 20px;\r\n");
      out.write("\tpadding-right: 5px;\r\n");
      out.write("\tborder: 1px solid #39B54A;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-shadow: 0 1px #20942B;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".action_record , .action_record:HOVER{\r\n");
      out.write("\tbackground: url(\"");
      out.print(request.getContextPath());
      out.write("/images/btngreen_bg.png\") repeat-x scroll center top;\r\n");
      out.write("\tcolor: #FFFFFF;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tfont-weight: bold;\r\n");
      out.write("\theight: 20px;\r\n");
      out.write("\tline-height: 20px;\r\n");
      out.write("\tpadding-left: 10px;\r\n");
      out.write("\tpadding-right: 5px;\r\n");
      out.write("\tborder: 1px solid #39B54A;\r\n");
      out.write("\tborder-radius: 10px;\r\n");
      out.write("\ttext-shadow: 0 1px #20942B;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#add_record_popup{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tbackground: none repeat scroll 0 0 #fff;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbox-shadow: 0 0 4px rgba(0, 0, 0, 0.698);\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#request_popup{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tbackground: none repeat scroll 0 0 #fff;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbox-shadow: 0 0 4px rgba(0, 0, 0, 0.698);\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("#approve_popup{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tbackground: none repeat scroll 0 0 #fff;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbox-shadow: 0 0 4px rgba(0, 0, 0, 0.698);\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#info_popup{\r\n");
      out.write("\tdisplay: none;\r\n");
      out.write("\tbackground: #fff;\r\n");
      out.write("\twidth: 800px;\r\n");
      out.write("\theight: auto;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tbackground: none repeat scroll 0 0 #fff;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\tbox-shadow: 0 0 4px rgba(0, 0, 0, 0.698);\r\n");
      out.write("\tfont-size: 14px;\r\n");
      out.write("}\r\n");
      out.write(".left_column{\r\n");
      out.write("\ttext-align: right;\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".right_column{\r\n");
      out.write("\ttext-align: left;\r\n");
      out.write("\twidth: 80%;\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".margin_left_5percent{\r\n");
      out.write("\tmargin-left: 5%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".width20percent{\r\n");
      out.write("\twidth: 20%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".merchant_filter{\r\n");
      out.write("\tborder: 1px solid #CCCCCC;\r\n");
      out.write("\tpadding: 6px;\r\n");
      out.write("\tmargin: 0px;\r\n");
      out.write("\t-webkit-border-radius: 3px;\r\n");
      out.write("\t-moz-border-radius: 3px;\r\n");
      out.write("\tborder-radius: 3px;\r\n");
      out.write("\twidth: 140px;\r\n");
      out.write("\tbox-shadow: 0 0 0 #000000, 0 3px 3px #EEEEEE inset;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("::-webkit-input-placeholder { font-style: italic; }\r\n");
      out.write("::-moz-placeholder { font-style: italic; }\r\n");
      out.write("::-ms-input-placeholder { font-style: italic; }\r\n");
      out.write("</style>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
