/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.56
 * Generated at: 2014-10-30 02:07:43 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.layouts.web;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import vn.onepay.common.SharedConstants;
import vn.onepay.account.model.Account;
import java.lang.String;

public final class header_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!-- Header -->\n");
      out.write("<div id=\"w_header\">\n");
      out.write("\t<a href=\"");
      out.print(request.getContextPath());
      out.write("/trang-chu.html\" class=\"logo_1pay\"></a>\n");
      out.write("\n");
      out.write("\t<div id=\"nav\">\n");
      out.write("\t\t<ul id=\"qm0\" class=\"qmmc\">\n");
      out.write("\t\t\t<li><a class=\"qmparent nav_menu");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuTrangChu?'_slc':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" href=\"");
      out.print(request.getContextPath());
      out.write("/trang-chu.html\">Trang chủ</a></li>\n");
      out.write("\n");
      out.write("\t\t\t<li><a class=\"qmparent nav_menu");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuDichVu?'_slc':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html\">Dịch vụ</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html?n=sms\">SMS Charging</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html?n=card\">Card Charging</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html?n=wap\">Wap Charging</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html?n=iac\">SMSplus Charging</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html?n=bank\">Bank Charging</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html\">Direct Charging</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath());
      out.write("/dich-vu.html\">Sub Charging</a></li>\n");
      out.write("\t\t\t\t\t\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li><a class=\"qmparent nav_menu");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuNhaPhatTrien?'_slc':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" href=\"http://dev.1pay.vn\">Nhà phát triển</a>\n");
      out.write("\t\t\t\t");
      out.write("</li>\n");
      out.write("\n");
      out.write("\n");
      out.write("\t\t\t<li><a class=\"qmparent nav_menu");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuCongDong?'_slc':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" href=\"http://forum.1pay.vn\">Cộng đồng</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://forum.1pay.vn\">Diễn đàn </a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://facebook.com/1pay.vn\">Facebook</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Twitter</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"#\">Google+</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/news/category.html\" class=\"qmparent nav_menu");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuTinTuc?'_slc':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\">Tin tức</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/news/category.html\">Tin hoạt động</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/news/category.html\">Sự kiện</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print( request.getContextPath() );
      out.write("/news/category.html\">Bản tin ngành nội dung số</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\n");
      out.write("\t\t\t<li><a class=\"qmparent nav_menu");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${menuHoTro?'_slc':''}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("\" href=\"");
      out.print(request.getContextPath() );
      out.write("/lien-he.html\">Hỗ trợ</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li><a href=\"http://help.1pay.vn\">Help center</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/dieu-khoan.html\">Điều khoản sử dụng</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/chinh-sach-thanh-toan.html\">Chính sách thanh toán</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/ban-quyen.html\">Bản quyền</a></li>\n");
      out.write("\t\t\t\t\t<li><a href=\"");
      out.print(request.getContextPath() );
      out.write("/lien-he.html\">Liên hệ</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li class=\"qmclear\">&nbsp;</li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t\t<!-- Create Menu Settings: (Menu ID, Is Vertical, Show Timer, Hide Timer, On Click ('all' or 'lev2'), Right to Left, Horizontal Subs, Flush Left, Flush Top) -->\n");
      out.write("\t\t<script type=\"text/javascript\">\n");
      out.write("\t\t\tqm_create(0, false, 0, 250, false, false, false, false, false);\n");
      out.write("\t\t</script>\n");
      out.write("\t\t<!--[if IE]><iframe onload=\"on_script_loaded(function() { HashKeeper.reloading=false; });\" style=\"display: none\" name=\"hashkeeper\" src=\"/blank\" height=\"1\" width=\"1\" id=\"hashkeeper\"></iframe><![endif]-->\n");
      out.write("\t</div>\n");
      out.write("\t<div id=\"account-header\">\n");
      out.write("\t\t<ul class=\"nav\">\n");
      out.write("\t\t\t");
      //  c:choose
      org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          //  c:when
          org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
          _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          // /layouts/web/header.jsp(72,3) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
          _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account_logined != null}", java.lang.Boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false)).booleanValue());
          int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
          if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("<li class=\"ui-button\">\n");
              out.write("\t\t\t\t\t<a href=\"#\" class=\"header-nav-link\" onclick=\"return false;\">\n");
              out.write("\t\t\t\t\t\t<span id=\"emsnippet-100eb3184c1c497f\">");
              if (_jspx_meth_c_005fout_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
                return;
              out.write("</span>\n");
              out.write("\t\t\t\t\t\t<span class=\"lbl_gray\">L");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account_logined_level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\n");
              out.write("\t\t\t\t\t</a>\n");
              out.write("\t\t\t\t\t<div class=\"sub-nav chat-bubble\" align=\"left\">\n");
              out.write("\t\t\t\t\t\t<ul>\n");
              out.write("\t\t\t\t\t\t\t<li>\n");
              out.write("\t\t\t\t\t\t\t\t<a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/profile.html\">\n");
              out.write("\t\t\t\t\t\t\t\t\t<div class=\"ava_box\">\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<img src=\"");
              out.print( request.getContextPath());
              out.write("/images/avatar.png\" border=\"0\" />\n");
              out.write("\t\t\t\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t\t\t\t<div>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<strong>");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account_logined.username}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</strong><br/>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<img alt=\"level\" src=\"");
              out.print(request.getContextPath());
              out.write("/images/level_chart.png\"><span style=\"color:#2C8F39;\"><strong>Level:</strong> ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account_logined_level}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("<br/>\n");
              out.write("\t\t\t\t\t\t\t\t\t\t<img alt=\"exp\" src=\"");
              out.print(request.getContextPath());
              out.write("/images/exp_point.png\"><strong>Exp:</strong> ");
              out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account_logined_exp}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
              out.write("</span>\n");
              out.write("\t\t\t\t\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t\t\t\t\t</a>\n");
              out.write("\t\t\t\t\t\t\t</li>\n");
              out.write("\t\t\t\t\t\t\t<div class=\"clear\"></div>\n");
              out.write("\t\t\t\t\t\t\t");

							Account account = (Account) request.getSession().getAttribute(SharedConstants.ACCOUNT_LOGINED);
							
if(account.isAdmin() || account.isOperator() || account.isShareHolder() || account.isReporter() || account.isBizManager() || account.isBizStaff() || account.isBilling()){
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/revenue-dashboard.html\">Báo cáo LNG</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 
if(!SharedConstants.MBIZ && (account.isAdmin() || account.isOperator() || account.isBizManager())){
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/kpi_chart.html\">Theo dõi kế hoạch</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 
if(!SharedConstants.MBIZ && (account.isAdmin() || account.isOperator() || account.isBizSupportManager())){
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/cdr/sms-cdr-filter.cdr\">Thử nghiệm nội bộ</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 

							if(!SharedConstants.MBIZ && account.checkRole(Account.ACCOUNT_STAFF_ROLE) && account.checkRoles(new String[]{Account.ACCOUNT_ADMIN_ROLE, Account.ACCOUNT_OPERATION_MANAGER_ROLE})){
							
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/cash-flow.html\">Quản lý dòng tiền</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 

							if(!SharedConstants.MBIZ && account.checkRole(Account.ACCOUNT_STAFF_ROLE) && account.checkRoles(new String[]{Account.ACCOUNT_ADMIN_ROLE, Account.ACCOUNT_OPERATION_MANAGER_ROLE, Account.ACCOUNT_SHARE_HOLDER_ROLE, Account.ACCOUNT_MERCHANT_MANAGER_ROLE, Account.ACCOUNT_BIZ_SUPPORTER_ROLE,  Account.ACCOUNT_CUSTOMER_CARE_ROLE})){
							
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/merchant-manager.html\">Quản lý Merchant</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 
if(!SharedConstants.MBIZ && account.checkRole(Account.ACCOUNT_STAFF_ROLE) && account.checkRoles(new String[]{Account.ACCOUNT_OPERATION_MANAGER_ROLE, Account.ACCOUNT_MERCHANT_MANAGER_ROLE, Account.ACCOUNT_BIZ_SUPPORTER_ROLE})){ 
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/merchant_profile_manager.html\">Quản lý Merchant Profiles</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 

							if(!SharedConstants.MBIZ && account.checkRole(Account.ACCOUNT_STAFF_ROLE) && account.checkRoles(new String[]{Account.ACCOUNT_OPERATION_MANAGER_ROLE, Account.ACCOUNT_BIZ_SUPPORTER_ROLE})){
							
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/provider_profile_manager.html\">Quản lý Provider's Profile</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
}

								if(account.checkRole(Account.ACCOUNT_STAFF_ROLE) && account.checkRoles(new String[]{Account.ACCOUNT_ADMIN_ROLE, Account.ACCOUNT_OPERATION_MANAGER_ROLE})){
							
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/email-announcement.html\">Thông báo Email</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 
	if(account.checkRole(Account.ACCOUNT_STAFF_ROLE) && account.checkRoles(new String[]{Account.ACCOUNT_ADMIN_ROLE, Account.ACCOUNT_OPERATION_MANAGER_ROLE, Account.ACCOUNT_MARKETING_MANAGER_ROLE, Account.ACCOUNT_MERCHANT_MANAGER_ROLE})){
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/manage-email-marketing.html\">Email Marketing</a></li>\n");
              out.write("\t\t\t\t\t\t\t");
} 
              out.write("<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/protected/profile.html\">Cấu hình</a></li>\n");
              out.write("\t\t\t\t\t\t\t<li><a href=\"");
              out.print( request.getContextPath());
              out.write("/logout.html\">Sign out</a></li>\n");
              out.write("\t\t\t\t\t\t</ul>\n");
              out.write("\t\t\t\t\t\t<div class=\"chat-bubble-arrow-border\"></div>\n");
              out.write("\t\t\t\t\t\t<div class=\"chat-bubble-arrow\"></div>\n");
              out.write("\t\t\t\t\t</div>\n");
              out.write("\t\t\t\t</li>\n");
              out.write("\t\t\t\t\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
          //  c:otherwise
          org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
          _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
          _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
          int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
          if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
            do {
              out.write("<li>\n");
              out.write("\t\t\t\t<div class=\"down\" id=\"top-login-wrapper\" style=\"padding-top:10px;\">\n");
              out.write("\t\t\t\t<a href=\"");
              out.print( request.getContextPath());
              out.write("/login.html\"><img src=\"");
              out.print(request.getContextPath());
              out.write("/images/door-open-in.png\"\n");
              out.write("\t\t\t\t\t\tborder=\"0\" align=\"absmiddle\" hspace=\"5\" /> Đăng nhập</a>\n");
              out.write("\t\t\t\t</div>\n");
              out.write("\t\t\t</li>\n");
              out.write("\t\t\t");
              int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
              if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
                break;
            } while (true);
          }
          if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
            _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
            return;
          }
          _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
        return;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\t\t\t$(document).ready(function() {\n");
      out.write("\t\t\t\t\t$('.ui-button').live('click', function() {\n");
      out.write("\t\t\t\t\t\tvar newClass= $(this).attr('class') + '';\n");
      out.write("\t\t\t\t\t\tif(newClass.indexOf(' active') > 0) {\n");
      out.write("\t\t\t\t\t\t\tnewClass = newClass.replace(/ active/gi,'');\n");
      out.write("\t\t\t\t\t\t} else {\n");
      out.write("\t\t\t\t\t\t\tnewClass = newClass.replace(/ active/gi,'') + ' active';\n");
      out.write("\t\t\t\t\t\t}\n");
      out.write("\t\t\t\t\t\t$(this).attr('class',newClass);\n");
      out.write("\t\t\t\t\t});\n");
      out.write("\t\t\t\t});\n");
      out.write("\t\t\t</script>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"clear\"></div>\n");
      out.write("</div>\n");
      out.write("\n");

	request.setAttribute("ALL_ACTIVED_CHARGING_SERVICES", SharedConstants.ALL_ACTIVED_CHARGING_SERVICES);

      out.write("<!-- / Header -->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fout_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:out
    org.apache.taglibs.standard.tag.rt.core.OutTag _jspx_th_c_005fout_005f0 = (org.apache.taglibs.standard.tag.rt.core.OutTag) _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.OutTag.class);
    _jspx_th_c_005fout_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fout_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
    // /layouts/web/header.jsp(75,44) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fout_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${account_logined.username}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
    int _jspx_eval_c_005fout_005f0 = _jspx_th_c_005fout_005f0.doStartTag();
    if (_jspx_th_c_005fout_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fout_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005fout_005f0);
    return false;
  }
}
